### ISSUE TITLE
Reading from a file via MockFileStream resets creation time

### ISSUE THREAD

**Issue by kodfodrasz** [tathamoddie/System.IO.Abstractions#122]
when having a mocked file in a mockfilesystem, and readfing from it mutates the LastWriteTime of the mocked file.
Here is an XUnit fact which can be used as a regression test to verify the problem, and the solution.
 
```
        [Fact]
        public void ReadingFromAFileDoesNotOverwriteIt() {
            // Arrange
            var fs = new MockFileSystem();
            var filename = @"C:\TestData\test.txt";
            var file = new MockFileData(@"This is just a test file

with test contents, which are not modified!");
            var lastmod = new DateTime(2012, 03, 21);
            file.LastWriteTime = lastmod;
            fs.AddFile(filename, file);

            // Act
            using (var reader = fs.File.OpenText(filename)) {
                var firstline = reader.ReadLine();
            }

            // Assert
            Assert.Equal(lastmod, fs.FileInfo.FromFileName(filename).LastWriteTime);
        }
```

**Comment by kodfodrasz** [comment]
the version where the problem was detected is: 2.0.0.112
Please consider extending the tests for creation and access times too!

**Comment by KenVanGilbergen** [comment]
I had the same when mocking the lastwritetime. I think it is because 'MockFileStream' runs internalflush on close and the mocked file is removed but not recreated correctly. Maybe save the file attributes before removing it and add them after creation? 
 
private void InternalFlush()
{
      if (this.mockFileDataAccessor.FileExists(this.path))      
{
//TODO: save file attributes
this.mockFileDataAccessor.RemoveFile(this.path);
}
      this.Seek(0L, SeekOrigin.Begin);
      byte[] numArray = new byte[this.Length];
      this.Read(numArray, 0, (int) this.Length);
this.mockFileDataAccessor.AddFile(this.path, new MockFileData(numArray)); 
//TODO: add file attributes
}
